### PR TITLE
Fixed responsiveness of image in card section in postVideoLarge component

### LINKED ISSUE #834: Improvement in "PostVideoLarge" Canvas in  our Cards section
## Problem

The `PostVideoLarge` Canvas does not look good in mobile views.

## Reproduction

1. Either open the website on mobile or click on inspect element on desktop
2. Go to the `Sidebar` section and then click on the `Cards` section
3. Click on the `PostVideoLarge` tab and see the view in the `Canvas` section

## Alternatives

It would be better if we can improvise this `PostVideoLarge` canvas in mobile-version.

## Screenshots

image

## Implementation

- [ ] I would try to implement the feature if this is a valid issue.

### PR DESCRIPTION
**Pull request by frappelatte28**
## Description
Image and card content in the cards section in postVideoLarge component were not responsive --used grid and media-query to fix the issue.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by frappelatte28** [comment]
@zackkrida @nimishbongale Kindly review the PR :)

**Review by zackkrida — CHANGES_REQUESTED** [review]
This looks great, but fyi there are existing responsive utilities. You can see them in use in some other files:

```bash
packages/vocabulary/src/styles/notification.scss
39:    @include mobile() {
74:    @include mobile() {

packages/vocabulary/src/styles/footer.scss
104:  @include tablet() {
114:  @include mobile() {

packages/vocabulary/src/styles/global_header.scss
112:  @include tablet() {
161:  @include desktop() {
190:  @include fullhd() {
227:  @include desktop() {
```

**Comment by frappelatte28** [comment]
@zackkrida I have made the requested changes but I am facing an issue while doing this. For mobile view it is responsive but when I cross the width of 1007px it is not showing the image. Here, I am attaching screenshots for the same. 
Please let me know what am I missing out.
CC_fix1
CC__fix1
Thanks!

**Review by zackkrida — APPROVED** [review]
Hi @frappelatte28 I pushed a small fix to your PR that resolves the issues. Flexbox can be difficult with images; they can either collapse and be invisible or stretch and be distorted quite easily. 

Nice work, thank you for this fix!

**Comment by frappelatte28** [comment]
Thank you for explaining and merging the pull request :-)

**Pull request merged**
