### PR TITLE
Sanitize path names

### LINKED ISSUE #47: Issue with building documentation & library
**Description**

After installing all dependencies and devDependencies using - `npm i --dev`
When I tried to build documentation using the command - `npm run build:documentation`
Also, produces the same error while trying to build library - `npm run build:library`

**Reproduction**

- Create a folder having space in the name like - `Creative Commons`
- Also folders having non ASCII values such as - `GSOC 2020 🚀`
- `git clone https://github.com/creativecommons/vocabulary.git`
- `npm i --dev`
- `npm run build:documentation`
- `npm run build:library`

**Expected behavior**

- Should allow clean build for even folders having space in their names

**Screenshots**

**Issue- with space in name**
image

**Issue with space along with non ASCII characters**
- Even though this shows a clean build, this generates new folders at the location
- Example name - `GSOC 2020 🚀`

**Without space in name**
image

**Conditions:**

 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Version: 79.0.3945.117

**Additional context**

- The issue is definitely due to space in folder name, to resolve it should resolving the build script at `documentation/build` work or something else, I am not sure.
- Additionally the issue is only caused when calling CLI commands from javascript files, as they are unable to handle the spaces or non ASCII characters, whereas nodes library can use those path properly.

**Want to take up?**

[Yes|No]
Yes

Would love some guidance on the same.

### PR DESCRIPTION
**Pull request by nilshah98**
**Fixes**

Partially addresses #47 by @nilshah98 

**Description**

- Sanitized path name for different OS, except Windows
- Sanitized by adding `\` to escape white space, so `Creative Commons` becomes `Creative\ Commons`

**Type of PR** 
This PR is a [feature|hotfix|refactor].
- Hotfix

**Technicalities**

- Added a function to sanitize paths, in `documentation/variables.js`
- Split by `/` and then sanitized each using regex - `path.replace((/(\s+)/g,'\\$1)'` and then joined again using `/`
- For windows OS, tried wrapping the path with single inverted commas and even double inverted commas as -`'C:\path\to\folder'`, but couldn't fix it.

**Tests**

**Screenshots**

**Windows Error**
image

**Ubuntu Works**
image

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by nilshah98** [comment]
Please review, @dhruvkb .
Thank You.

**Comment by dhruvkb** [comment]
@nilshah98 this looks good. I've found that putting the path in "double quotes" and 'single quotes' also works on Linux. For an edge case, try putting an emoji or a non-ASCII Unicode character in the directory name.

Here's [an answer](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks) for achieving this on Windows. Do give it a try as well.

**Comment by nilshah98** [comment]
**Windows**
The issue still persists even after using `^` (carat) to escape the white space
image

**non-ASCII Unicode Testing**
On Ubuntu 18.04 works pretty smoothly
image

Also, let me know is you need me to shift from using `\` escape characters to using `" "` double quotes for escaping white space on Linux systems.

**Review by dhruvkb — APPROVED** [review]

**Comment by nilshah98** [comment]
Just realised, there are other build scripts I need to sanitize as well, tokens and library that is.
I'll post another issue and PR by tonight.

**Comment by brylie** [comment]
@all-contributors please add @nilshah98 for code

**Comment by nilshah98** [comment]
Thanks a lot team, for acknowledging my contributions!
Means a lot! 😄

**Pull request merged**
