### PR TITLE
#issue 856, changed component Preview to Canvas

### LINKED ISSUE #856: Changing Preview component to Canvas
## Description
After Storybook release v6.0 [Link](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#previewprops-renamed) .The preview component has been renamed to canvas.In the current codebase there is a lot of use of `<Preview>` component.

## Expectation
Though these changes are backward compatible but we should rename the component for future reference and as per current documentation there is no use of <Preview> component thus future developers may have a problem in implementing it.

## Additional context
I m looking forward for discussion on this issue

## Resolution
- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Shukshi**
## Fixes 
Fixes #856 by @shukshi

## Description
This pull request changes all the component named "Preview" to "Canvas"

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Shukshi** [comment]
Changed components from Preview to Canvas

**Comment by nimishbongale** [comment]
@Shukshi 

Please fill out the PR template to the best of your knowledge. Also, while we are at it, does the Canvas component support the mdxSource prop?

**Comment by Shukshi** [comment]
Hey, sorry for not filling it before. I've filled the PR template to best of my knowledge. And sorry I don't have idea about Canvas component support the mdxSource prop.

**Review by zackkrida — APPROVED** [review]

**Comment by zackkrida** [comment]
Hi all, I've reviewed the PR and it looks good. The Canvas component supports all the same props as Preview did, it's really just a rename, so there shouldn't be any compatibility issues.

**Pull request merged**
