### PR TITLE
Update some dependencies to reduce vulnerability warnings

### LINKED ISSUE #988: Update initial dependencies to reduce vulnerability warnings
`npm` is warning us about several vulnerabilities. However, it may not be possible to resolve them all, due to the complexity of our dependency tree.

## Task

- [ ] update as many dependencies as possible with `npm audit fix --legacy-peer-deps`

### PR DESCRIPTION
**Pull request by brylie**
Closes #988 

There are still a lot of issues reported, but at least some are addressed here.

### CODE REVIEW

**Comment by brylie** [comment]
@MuluhGodson, would you please test this pull request to make sure the project works as expected in your development environment?

**Comment by MuluhGodson** [comment]
@brylie Okay. Doing that now. 
But I am confused as to why the CI scripts aren't being executed. They just display as required but not executed. 
I think they are supposed to run each time an issue is opened or a PR is made to the `main` branch

**Comment by brylie** [comment]
I'm not sure why they aren't executing either. There may be an answer on SO:

https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported

**Comment by MuluhGodson** [comment]
`lint`, `test`, and `build`, and `serve` commands all work with no errors as of now.

**Pull request merged**
