### PR TITLE
Progress layout

### LINKED ISSUE #112: Add the Progress layout
Add the Progress layout and its components: the white boxes to indicate the different states. The section is in Design Library.

### PR DESCRIPTION
**Pull request by jahnvigupta**
## Fixes

Fixes #112 by @panchovm 

## Description

It adds Progress Layout to the vocabulary.
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
Hi @jahnvigupta, this feels like a very good start but could use some corrections:

- [ ] Switch hardcoded colors (hex values) to vocabulary's  [color variables](https://github.com/creativecommons/vocabulary/blob/master/src/styles/color.scss)
- [ ] Remove any inline styles
- [ ] Avoid floats; try [flexbox instead.](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
- [ ] Avoid _hardcoded heights_ like `height:77px;`. A `min-height` would be better, but most of the time the height should be determined by the contents.

**Comment by jahnvigupta** [comment]
@zackkrida is it still needed? Because I think it has been added as part of internship.

**Comment by zackkrida** [comment]
You could and should definitely port over the component from https://github.com/creativecommons/chooser

If you want I can just close this too, totally up to you :)

**Comment by jahnvigupta** [comment]
@zackkrida I will do it.

**Comment by jahnvigupta** [comment]
@zackkrida I am getting this error.
Screenshot from 2020-08-04 23-05-27

**Comment by zackkrida** [comment]
@jahnvigupta make sure you pull down the latest code and `npm install`, that should fix it.

**Comment by jahnvigupta** [comment]
@zackkrida you may close this PR.

**Pull request closed without merging**
