### PR TITLE
[WIP] Add svg icons

### LINKED ISSUE #679: SVG icons pack for Fonts
## Problem
Font icons are not great. SVG icons are.

## Description
Present situation: Icon packed into a font are not great.

- There are many icons now, all but a couple of which are just subsetted from Font Awesome
- News icons are added all the time and the process is not friendly for contributors
- Since every new icon is a font-rebuild, it takes time and kills the possibility of caching
- The process can not be automated at all at any stage and that's no fun for any of us
- Many sites use these icons, none use the full set but have to download the entire font file as a whole
- Each icon is mapped to a rather arbitrary code-point

Suggested solution: We replace the icon font with an SVG collection

- They are light weight and scalable and offer all the benefits of styling with CSS like a regular font
- They can be subsetted by the app that uses Vocabulary and then minified by the respective bundlers
- They can be directly loaded into the collection with copy-paste, no need for long builds
- They are smaller than fonts in size
- They can be cached
- They can have semantic meaningful names

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #679 by @dhruvkb 

## Description

Currently, this PR only adds the svg files used in Vocabulary icon font, optimized with `svgomg`. All icons have `viewbox`, set to 30x30px, and don't have `width` or `height` specified for responsibility. 

## Technical details

The icons are placed into folders, eg. 'caret-down' icon can be found at `svg\arrows\caret-down.svg`. Is it better to have a flat structure without folders?

We still need to: 

- [ ]  add a component that allows users to copy icon inline svg and download the icon.

- [ ]  document how to use the icons

- [ ]  add the 4 'arrow' icons that are available in the Vocabulary font.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
You covered almost all of the icons 👍 !

**Review by dhruvkb — CHANGES_REQUESTED** [review]
The classification seems to be off in certain cases when compared to [the existing set](https://cc-vocabulary.netlify.app/?path=/docs/tokens-icons--figma).

**Comment by obulat** [comment]
> The classification seems to be off in certain cases when compared to [the existing set](https://cc-vocabulary.netlify.app/?path=/docs/tokens-icons--figma).

Thank you, @dhruvkb. Could you tell me where it's off?  I've checked again but couldn't find any icon that's not in the right category. The current version has two levels of categories (`symbols\hieroglyphs`), I only used one, as I think two levels will be too cumbersome when importing. Do you agree?

**Comment by dhruvkb** [comment]
@obulat that's actually a fair point! 👍 Any more levels of classification would make the organisation cumbersome. But could you move RSS from symbols to a logo? The original classification under symbols is incorrect.

**Comment by zackkrida** [comment]
@obulat `storybook-icon-gallery` is a great find, excited to see it when the implementation is ready.

**Comment by obulat** [comment]
I've implemented the icon gallery for all svg icons using `storybook-icon-gallery`. Currently, when you click 'copy', it copies the file path, for example: `@creativecommons/vocabulary/assets/svg/arrows/chevron-down.svg` for `chevron-down` icon.
In a Vue app with svg-inline-loader installed, or a Nuxt app with `@nuxt/svg` module, as in cccatalog-frontend, you can use this icon as follows:

js:
```
import chevronDown from '@vocabulary/fonts/src/assets/svg/cc/cc-logo.svg?inline'
```
template:
```
<span class="icon"><chevronDown /></span>
```
The icon's color and size can be changed with css applied to the span.

Using the icons like this, we only import the specific icon's inline svg, and don't include icons we don't use in the bundle. 

#### Some issues I would like to discuss:
- Usage: 
There are also ways of using svg sprites, or using svg icons as icon font, where we do not need to import each icon manually. Is it an idea worth pursuing?
- Accessibility:
I haven't done much research on svg icon accessibility, but we probably need to add 'alt' or 'title' tag somewhere.


##### I've also done some manual editing of the icons:
- removed a circle path from the CC icons so that they can be used with 'has-background-white' class.
- removed <g> tags and <clip-path> tags with ids: this can cause a bug where the clip path from one icon is applied to other icons if they have the same ids.

**Comment by dhruvkb** [comment]
@obulat icon fonts are not good. We are actually moving to SVG to stop using icon fonts. As for the accessibilty, we might have to set `alt`, `title` and also ARIA attributes on these SVGs.

**Comment by zackkrida** [comment]
@dhruvkb @obulat Some thoughts:

## Regarding a11y

We do **not** want to set any `alt`, `aria-`, or `title` attributes on the icons. Those should all be handled by the user consuming the icon, as they are specific to the context in which the icons are being used. For example, someone using an icon as a button vs. someone using an as an image above a headline would have very different a11y needs, and providing defaults could actually be harmful.

## Usage

Users should either import individual icons, _or_ copy inline svg code directly. I would like to be able to support these two options. I imagine we would need a custom/forked version of `storybook-icon-gallery` or a custom React component to offer two copyable sources (one button for an import, one for the inline svg tag).

Personally, I don't worry about users not having access to all of the icons, as they would in an icon font. Even when using an icon font you need to know the name and appearance of every icon available, which usually means jumping to their documentation and copying the icon name, so it would be a similar workflow. I think the benefits significantly outweigh the cons here.

**Comment by Dhruvi16** [comment]
Makes sense to me. @zackkrida Plus did you tag me instead of @dhruvkb? 😅

**Comment by zackkrida** [comment]
@Dhruvi16 I always do that 🤦 GitHub always shows me both of you, always in different order. Oops!

**Comment by Dhruvi16** [comment]
yeah! cons of having similar names but sometimes you get tagged in an interesting conversation so not so much of a con 😆

**Comment by zackkrida** [comment]
From now on i'll always type @Dhruvi16 / @dhruvkb  just to be safe.

**Comment by obulat** [comment]
I am closing this PR in favor of #756

**Pull request closed without merging**
