### PR TITLE
WIP: Fix stories of missing components (button, tabs, select, etc)

### PR DESCRIPTION
**Pull request by sadn1ck**
## Fixes

Related to #905 and #932  by @brylie and @dhruvkb 

## Description
WIP

- [x] Button Stories
- [x] Tabs
- [x] Select
- [x] Donate Button
- [x] VButton
- [x] VCheckbox
- [x] VHeader
- [x] VRadio
- [x] VLocale
- [x] VModal

## Technical details

@brylie I have made some commits, can you have a look whenever you have time? I can continue on with the remaining ones then.

~~Also, I refrained from touching the Vue component stories right now since I'll need to read up on how they should be integrated into storybook, and these changes were pretty simple in-place.~~

Started work on the vue components as well! Simply put them in similar folder structures as other components.

## Screenshots

<details>
<summary>Fix screenshots of donate button and tabs</summary>

image
image

</details>

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sadn1ck** [comment]
## Issues with VHeader and VModal

### VHeader

- ChooserLogo svg import in the VHeader story is not resolving to the proper path

<details>
<summary>ChooserLogo svg import error</summary>

```js
// VHeader.stories.js
import ChooserLogo from '@/assets/logos/products/chooser.svg';
// OR
import ChooserLogo from '../../assets/logos/products/chooser.svg';
// both produce this same resolution error
```

image


</details>


### VModal

- vmodal uses an external dependency `focus-trap-vue`, what should I do regarding that? Should I install as a dependency?
- removing that doesnt break the component, but I assume that is necessary to keep focus on the modal for accessibility reasons

---

I've updated the remaining stories as mentioned in the opening comment of this PR.

**Comment by brylie** [comment]
> vmodal uses an external dependency focus-trap-vue, what should I do regarding that? Should I install as a dependency?

Since the dependency seems relatively well maintained, we can install it.

**Comment by brylie** [comment]
> ChooserLogo svg import in the VHeader story is not resolving to the proper path

Perhaps follow a similar pattern to [/src/stories/vocabulary/product_logos.stories.mdx](https://github.com/creativecommons/vocabulary/blob/restructure/src/stories/vocabulary/product_logos.stories.mdx)?

**Comment by sadn1ck** [comment]
> > ChooserLogo svg import in the VHeader story is not resolving to the proper path
> 
> Perhaps follow a similar pattern to [/src/stories/vocabulary/product_logos.stories.mdx](https://github.com/creativecommons/vocabulary/blob/restructure/src/stories/vocabulary/product_logos.stories.mdx)?

I just checked, those stories with the svg's also have similar issues. (404 for some reason)

<details>
<summary>import errors</summary>

image

</details>

**Comment by brylie** [comment]
Are your latest changes pushed to GitHub? I can try as well.

@dhruvkb, any suggestions?

**Comment by sadn1ck** [comment]
> Are your latest changes pushed to GitHub? I can try as well.

I haven't added the malfunctioning VHeader story yet, I assume you're asking about that.

**Comment by brylie** [comment]
Yes, I'm trying to test it currently.

**Comment by sadn1ck** [comment]
> > Are your latest changes pushed to GitHub? I can try as well.
> 
> I haven't added the malfunctioning VHeader story yet, I assume you're asking about that.

Found a possible solution:
In package.json
```json
"serve": "start-storybook -p 6006 --ci -s ./src/assets"
```
serves the assets directory at `/`, so I can now access them via `logos/etc`, the Logos stories are now working properly (some errors logged, I'll have a look)

But the VHeader text is now white for some reason? Have a look at the GIF I have attached.

<details>
<summary>white text, but images working</summary>

gaCIj9s8ex

</details>


### Found the bug [here, links were made white](https://github.com/creativecommons/vocabulary/blob/restructure/src/components/header/header.scss#L1)

**Comment by brylie** [comment]
> Found a possible solution:
> In package.json
>
> "serve": "start-storybook -p 6006 --ci -s ./src/assets"

That solution seems fine to me. Just make a note in the README explaining *why* the `-s ./src/assets` flag is needed, so we will remember.

**Comment by sadn1ck** [comment]
Alright, I think that's all of them. Have a look whenever you can! @brylie @dhruvkb 

In the meantime I'll see if there are any errors in the other stories (found some issues in the Logos one)

(dunno why adding a line to README changed the entirety of the file for some reason??)

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@sadn1ck great work on the migration of stories. Can you delete the redundant and unused code from `packages/`? The aim is to completely get rid of that directory and effectively end the monorepo structure.

**Comment by sadn1ck** [comment]
> @sadn1ck great work on the migration of stories. Can you delete the redundant and unused code from `packages/`? The aim is to completely get rid of that directory and effectively end the monorepo structure.

Yep I will, just wanted a review before going ahead with nuking code haha.

**Comment by sadn1ck** [comment]
Removed duplicated code of whichever components are fixed in this PR, lmk if you want me to remove the others as well. I think the `table`, `tabs` are already ported to the vue-cli part?

**Comment by brylie** [comment]
@sadn1ck is this PR ready for review by @dhruvkb? If so, please switch the status from Draft to Ready for Review.

**Comment by sadn1ck** [comment]
> @sadn1ck is this PR ready for review by @dhruvkb? If so, please switch the status from Draft to Ready for Review.

Done

**Comment by brylie** [comment]
@dhruvkb said they will be able to review this pull request after office hours.

**Comment by dhruvkb** [comment]
I'll definitely get this done today. Sorry for all the delays, it's been a hectic week.

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@sadn1ck so I went through the PR and here are some changes. 

1. Keeping Vue components with Vocabulary counterparts. The Vue components that map to Vocabulary styles should be placed adjacent to them.

| Vue | Vocabulary |
|-|-|
| VHeader | header.scss |
| VCheckbox | form.scss |
| VRadio | form.scss |
| VLocale | locale.scss |
| VModal | modal.scss |
| VButton | button.scss |

2. The story for Vue component `Tabs` has not been migrated yet.

3. The `Donate Button` is just a different variant of `Button`, put the stories along with the stories for `Button` itself.

4. Delete the `packages/` directory to make sure nothing important is left over there. All build scripts should work after its deletion.

5. Compare the stories from the following sites to ensure that we're not missing anything.
- https://cc-fonts.netlify.app/
- https://cc-vocabulary.netlify.app/
- https://cc-vue-vocabulary.netlify.app/

**Comment by sadn1ck** [comment]
@dhruvkb Some clarifications:

- As in I keep the vue component stories and the normal vocabulary stories in the same folder? 

- There's 1 normal donate button already in the vocab buttons stories, and the other Donate Button is a vue component, so should I put that along side the VButton stories?

- Also, should I create another category for Vue components? Or just beside their vocabulary counterparts

Will get the rest done as soon as I can 👍🏼

**Comment by dhruvkb** [comment]
1. Yes, keep them together (you can add a Vue section at the end in the title path).
```
- Component
  - Vue/
    - .., Vue stories
  - ... normal stories
```
2. Yes, so the story heirarchy will be
```
- Button
  - Vue/
    - ... VButton stories
    - ... Donate Button stories
  - ... button stories
  - ... donate button stories
```

**Comment by sadn1ck** [comment]
I have done the requested changes, please have a look whenever you can. (Also deleted packages/ after confirming that everything was ported to new project root)

But also a lot of components have this similar rendering issue logged on browser console -
```
Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.
```
- [x] Sidebar menu
- [x] Table of Content
- [x] Table of Progress
- [x] Cards
- [ ] Profile Image Custom Size
- [ ] Combined Header
- [x] Checkbox
- [x] Input
- [x] Textarea
- [x] Color (last, tomato background part?)
- [x] Spacing
- [x] Typography
- [x] Icons - Logos/Product

@brylie @dhruvkb can you confirm you face a variant of this error logged in the browser console? How should we tackle this?

EDIT: Okay, need to fix them in a similar manner to the ones we fixed at the start (wrap in a div, didn't mentally connect the errors till now)

EDIT 2: The logo svgs have style tags inside the html, so they are throwing errors


<details>
<summary>error</summary>

`Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.`

</details>

**Comment by sadn1ck** [comment]
Fixed logging errors in most components, not sure what to do with-

- Custom Sized Profile Image: has a style tag which i can move to external scss file, but then it won't show up in the code unless I duplicate some of it, I think
- Combined Header, I actually can't understand where the error is coming from

Latest changes pushed, you can have another look.

**Comment by brylie** [comment]
Ping @dhruvkb

**Comment by dhruvkb** [comment]
Thanks for the ping! I'll take a look very soon.

**Review by dhruvkb — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @sadn1ck for code

**Pull request merged**
