### PR TITLE
Add compact version of notification component

### LINKED ISSUE #466: A minimal notification component [Feature Request]
## Problem

The CC Search Extension mockup uses a small, minimal notification component that any of the current Vocabulary notification component is not able to replicate (unless the padding, font-size and width is overridden). See the `home bookmarked` [Figma mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) to see the intended design of notification component.

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by makkoncept**
## Fixes

Fixes #466 by @makkoncept 

## Description

Add a compact version of the notification component to the vocabulary. This will be used in the CC Extension ([Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=942%3A696)). 

- I named this `Compact Notification` and used the class name `is-compact`
- According to the Mockup, the size of the notification text should be 16px, therefore I used a paragraph tag for it.
- Did not hardcoded the background color and used Bulma helper class `has-background-danger-light` because in the extension this component will also be used for showing errors. For that, `has-background-danger-light` will come in handy.

## Screenshots

Storybook screenshot

Screenshot from 2020-08-06 02-15-04

With a width of 300px(added through developer tools) to mimic the mockup.

Screenshot from 2020-08-06 02-15-33

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by makkoncept** [comment]
@hugosolar Please review.

**Comment by makkoncept** [comment]
Also, in the extension, this notification component will only be used to show a message and the user is not expected to interact or click on this. So, I think we can make a `notification-container` a `div` or a `span` instead of  `a` tag so that the underline is not shown on hovering. Shall I do so?

**Comment by hugosolar** [comment]
yes @makkoncept that makes perfect sense, go ahead

**Review by hugosolar — APPROVED** [review]
It looks great!

**Pull request merged**
