### PR TITLE
Added Textarea component

### LINKED ISSUE #376: Add a TextArea component
**Description**

A `TextArea` component can be added to the `vocabulary` as it is used many times on the websites.

**Problems solved**

Consistent design over all the websites.

**Additional context**

image

**Want to take up?**

[Yes]

### PR DESCRIPTION
**Pull request by rajat2502**
## Fixes

Fixes #376  by @rajat2502 

## Description

Added a `textarea` component to the vocabulary.

## Technical details

Added `textarea` class in the `form.scss` and made a new mdx file for the component.

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

### CODE REVIEW

**Comment by rajat2502** [comment]
@dhruvkb @panchovm Please let me know if this is fine according to the design and implementation.

**Comment by dhruvkb** [comment]
It looks fine to me, although I'm not sure if we'll need the three size variants. Anyways, we should probably wait till @panchovm has added the designs to the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library) Figma doc so that we can link to the Figma node in the Design tab.

**Comment by rajat2502** [comment]
> I'm not sure if we'll need the three size variants

Yeah, I was also confused about this so just did according to the input.

**Comment by dhruvkb** [comment]
@rajat2502 actually `<input>` needs the larger variant as it is used on the CC Search homepage.
image

Not sure if there's going to be a similar requirement for `<textarea>`.

**Comment by rajat2502** [comment]
Okay, I will make the changes if we don't need the other variants.

**Comment by dhruvkb** [comment]
Let's wait for @panchovm's designs before we delete any efforts.

**Comment by rajat2502** [comment]
> Let's wait for @panchovm's designs before we delete any efforts.

Yeah sure.

**Comment by fcoveram** [comment]
I updated the textarea component in the Design Library. [Here is the link](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A250&viewport=-4677%2C60%2C0.9019354581832886) to the page.

**Comment by rajat2502** [comment]
I have updated the component according to the design, Please review.

**Comment by rajat2502** [comment]
Hey @dhruvkb, any changes on this one?

**Comment by dhruvkb** [comment]
@rajat2502 I'll review it today. Sorry I missed this on the weekend else would have shipped with `1.0.0-beta.16`.

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
