### PR TITLE
Changed the column layout of the footer

### LINKED ISSUE #322: Column layout of footer to match the design
**Description**
The design [Footer @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24) needs to match with the code/layout of the footer, presently I feel like it's not aligned completed with the design

**Alternatives**
I was working on an [issue](https://github.com/creativecommons/vue-vocabulary/issues/196) and this issue was noticed

---

cc_footer

In the above image the 1st box/design almost represents the column layout of the figma design.   
The 2nd one is the current layout which is present in the vocabulary now.   
The 3rd one is the layout which I am proposing.   

We can't go with the first one cause for the mobile devices the links will appear below the logo but the address and social media icons should appear. So I made the 3rd one which will be same as the present layout in the mobile devices and will match the design in the desktop resolutions

**Additional context**
I implemented my design to test things and this is what it looks like
footer_demo_story
**Want to take up?**
Yes

### PR DESCRIPTION
**Pull request by hemanth-hk**
## Fixes
Fixes #322 by me

## Description
This adds the new layout described in the issue's body

## Screenshots
vocab_footer_new

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open-source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open-source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    the person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by hemanth-hk** [comment]
@dhruvkb Please review this and tell me the changes, if any

**Review by dhruvkb — APPROVED** [review]
The changes match the design in Figma. Since @brenoferreira and @hugosolar might be using it, their approval is also needed.

**Comment by dhruvkb** [comment]
@hemanth-hk you also need to [update the snaphsot](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page) if you want the ["Snapshot test" to pass](https://github.com/creativecommons/vocabulary/pull/323/checks?check_run_id=598777521).

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@hemanth-hk we need a re-sync, please and thank you.

**Comment by krysal** [comment]
Hey @hemanth-hk @dhruvkb what remains to be done here? It would be cool to have the correct footer layout and there are several issues that depends on this. How can someone else help?

**Comment by dhruvkb** [comment]
@krysal only the conflicts need to be resolved. I was hoping @hemanth-hk would be available to do this but if he isn't, I'll resolve the issues and merge it. Thanks for bringing this up.

**Pull request closed without merging**
