### PR TITLE
[Vue] Bye-bye knobs, hello controls! And more.

### LINKED ISSUE #660: Migration of @storybook/addon-knobs to @storybook/addon-controls
## Description
Storybook recommends the usage of `addon-controls` over `addon-knobs`.
`addon-knobs` may soon be deprecated.

## Task
Migrate `@storybook/addon-knobs` to `@storybook/addon-controls` in all 3 packages.

## Additional context

- https://www.npmjs.com/package/@storybook/addon-controls

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Related to #667 by @zackkrida 

## Description

This PR does a few things:

- Switch from storybook knobs to controls, delete old knobs controls
- Add a new button component
- Add the boxed variation to the tabs component

## Technical details

Stories are now using the [args](https://storybook.js.org/docs/react/writing-stories/args) feature in the `CSF` component format. Note that these stories _can_ be imported into `.mdx` files in instances where we need to write a lot of supporting documentation and would prefer to use markdown.

## Tests

Please review locally but also review the netlify deploy preview (which is fixed 🎊). Also, lint CI is failing due to an eslint dependency error that I am unable to replicate locally.  Any help there would be huge too.

## Screenshots

Screen Shot 2020-09-14 at 11 32 31 AM
Screen Shot 2020-09-14 at 11 32 35 AM
Screen Shot 2020-09-14 at 11 32 28 AM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
Nice PR title 👌!

**Comment by zackkrida** [comment]
@dhruvkb reminder ping for you to review this when you can :) thanks! i'll have a full-time staffer or two peek at it this week too.

**Review by dhruvkb — APPROVED** [review]
We had previously decided that simple components like buttons and input fields will not have Vue counterparts. Apart from this, this is great 👍

**Comment by zackkrida** [comment]
> We had previously decided that simple components like buttons and input fields will not have Vue counterparts

Interesting! Is the idea then that `vue-vocabulary` is meant to be a _complement_ to `vocabulary`, used to add interaction when needed, rather than a _standalone_ vue implementation of the design library? I can see pros and cons to both approaches. I'll add some discussion of this to the meeting agenda

**Pull request merged**
