### PR TITLE
added prettier to the repo and as a pre-commit hook

### LINKED ISSUE #406: Adopt Prettier for code formatting
We want to ensure clean and consistent code style/formatting. One simple step would be to add Prettier as a `devDependency` to the project. Prettier may already be a transient dependency of the Vue CLI, but we will need to verify whether this is true.

## Task

- [ ] add Prettier as a `devDependency` for this project
- [ ] add instructions to our README for the use of Prettier
- [ ] consider how to automate code formatting via Prettier (e.g. via Git hooks)
- [ ] consider whether it is necessary to modify our `ci-lint` script to validate code using Prettier

## Original issue
**Description**
Since the project is being actively worked on by many developers, we need to ensure code quality is maintained consistently across the project. This is most efficiently achieved by
- creating a code style document for developers to follow
- setting up ESLint to catch cases where the code style is being missed
- setting up more comprehensive tooling to catch these cases in PRs

**Problems solved**
A clear, organised and well-maintained codebase is always a joy to contribute to.

### PR DESCRIPTION
**Pull request by Dishebh**
## Fixes

Fixes #406  by @dhruvkb 

## Description
Added prettier to the repo and as a pre-commit hook.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
Prettier has practically changed every file in the entire repository. That's a drastic step and I'm not comfortable taking it without having everyone in the team on board.

**Comment by Dishebh** [comment]
@dhruvkb, makes sense :)

**Comment by Dishebh** [comment]
Is there a way I could request review from the other core members? :sweat_smile: :

**Comment by dhruvkb** [comment]
I tagged @kgodey to review it and also suggest other people who should have a say on the matter.

**Comment by zackkrida** [comment]
Hi @Dishebh,

We definitely want to introduce prettier into the repository soon, but we need to be very careful about migrating over at a time when we have minimal open prs, so we can minimize merge conflicts and issues with contributors. We will also want to introduce a precommit hook to make sure prs are styled.

I am going to close this for now, I will let you know when we are ready to try this again to check if you want to help. Thank you!

**Comment by Dishebh** [comment]
@zackkrida thanks for filling me up here :) Please let me know whenever you decide to go forward with the issue.

**Pull request closed without merging**
