### PR TITLE
Fix Link cards code examples

### LINKED ISSUE #719: Link and LinkBorder cards do not show the full code
## Description

[Link card](https://cc-vocabulary.netlify.app/?path=/docs/layouts-cards--link) and [LinkBorder card](https://cc-vocabulary.netlify.app/?path=/docs/layouts-cards--link-border) components examples don't show the full code, so to replicate them the code has to be inspected.

## Reproduction

1. Go to the previous links and click "Show code" below the component preview.
2. Notice elements `<article>` for wrapping classes and anchor `<a>` are missing.

## Expectation

The examples should show the full code.

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #719 by @krysal.

## Description

This makes display all the code for the examples of **Link** and **Link Border** cards. Also changes styles a bit to allow make cards _without a link at the bottom_, as shown in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=776%3A133).

## Screenshots

Captura de pantalla de 2020-10-13 00-12-04

Minimalist link border card.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
The docs changes look good to me, although I do need to ask why you changed the card styles for the examples. Were the styles not matching up with the Figma files?

**Comment by krysal** [comment]
@dhruvkb yes, just a bit. I needed to use a Link Border card **_without a link at the bottom_** (just as simple as the one shown in the picture) for the [caselaw](https://github.com/creativecommons/caselaw) site, but with previous styles the padding were quite bigger without the `.has-bottom-link` class. The `.card-pretitle` class didn't exist till now, I needed something like this for the text before the title of the card.
I also increased the `line-height` of link card titles to make it look more like the designs but if this is too much I think we can't revert it.

**Comment by dhruvkb** [comment]
Typically changes to design need approval from @panchovm. Can you share the before/after versions so that we can get his approval on the change? That would also be helpful if we need to make the necessary changes in Figma as well.

**Comment by fcoveram** [comment]
Here are the card components.

Screen Shot 2020-10-13 at 17 32 16

And here the cards in the mockup.

Screen Shot 2020-10-13 at 17 32 36

I think we are using the `link filled` component but with different text styles. Does the component allow that style change?

**Comment by krysal** [comment]
@dhruvkb ok, let me explain it, Figma designs do not need to change because I based the styles changes on what is there.
Hopefully with these images my point should be clearer.

I needed a component similat to this but in white background with borders (for [creativecommons/caselaw#47](https://github.com/creativecommons/caselaw/issues/47)):

card link border
 
It is already present in Figma. The problem is that with current card styles the results is:

Captura de pantalla de 2020-10-13 19-58-28

<details>
<summary>Code used:</summary>

```html
<article class="card entry-post link">
  <a href="#">
    <div class="card-content">
      <span class="title is-h4 padding-bottom-normal">Short sentence</span>
      <h2 class="card-title">This is a Title of a page or a section</h2>
    </div>
  </a>
</article>
```
</details>

As you can see the padding is quite bigger and the gap between the short sentence and the title is small.

This is an alternative with `.has-bottom-link` class that keeps the usual padding but still seems odd that it's linked to that class.

Captura de pantalla de 2020-10-13 20-48-22


<details>
<summary>Code used:</summary>

```html
<article class="card entry-post link">
  <a href="#">
    <div class="card-content has-bottom-link">
      <span class="title is-h4 padding-bottom-normal">Short sentence</span>
      <h2 class="card-title">This is a Title of a page or a section</h2>
    </div>
  </a>
</article>
```
</details>

So this PR aims to fix those issues with link cards, and enable to do link border cards like the first I mentioned. The result is:

Captura de pantalla de 2020-10-13 20-57-10

See it [live here](https://deploy-preview-720--cc-vocabulary.netlify.app/?path=/story/layouts-cards--link-border).

**Comment by zackkrida** [comment]
@panchovm Could you re-review the feedback here? Thank you.

**Comment by fcoveram** [comment]
It looks perfect! Thanks @krysal

**Review by fcoveram — APPROVED** [review]

**Comment by krysal** [comment]
I noticed a little problem with `.card-pretitle` on dark backgrounds, the color should change the same with `.card-title`:
Captura de pantalla de 2020-10-22 12-09-52
So I made the change for that, to be used with the brand colors as usual.
Captura de pantalla de 2020-10-22 12-42-48

**Comment by zackkrida** [comment]
Great work, thanks @krysal 🎉

**Pull request merged**
