### PR TITLE
Changed order of subheadings

### LINKED ISSUE #380: Change order of subheadings in Overview
Change the order of the `subheadings` of a `principles` in the `overview` page of the storybook.
The `Meaning` should be the first subheading but better reader's experience.

### PR DESCRIPTION
**Pull request by rajat2502**
## Fixes

Fixes #380  by @rajat2502

## Description

Changes the order of subheadings on the Overview page of the storybook.

## Screenshots

image

## Checklist
 
- [x ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Please checkout the contents of the `package-lock.json` file so as to remove it from the PR.

**Comment by rajat2502** [comment]
> Please checkout the contents of the `package-lock.json` file so as to remove it from the PR.

@dhruvkb I have made the changes.

**Comment by rajat2502** [comment]
@kgodey Please review.

**Review by dhruvkb — APPROVED** [review]
The new order does seem more logical to me.

**Comment by kgodey** [comment]
Sorry I never got to this, the order change is fine with me.

**Pull request merged**
