### PR TITLE
modify header component to match figma styles

### PR DESCRIPTION
**Pull request by hugosolar**
**Description**
Header component style modification to match Figma designs:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=179%3A0

**Type of PR** 
This PR is a refactor.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by brenoferreira** [comment]
Could you add a storybook to this header so we can see what it looks like?

**Comment by hugosolar** [comment]
> Could you add a storybook to this header so we can see what it looks like?

yup, sorry... my bad

**Comment by brenoferreira** [comment]
Screen Shot 2020-01-27 at 12 02 02
The alignment in this case looks a bit strange. Maybe the logo should be centrally aligned with the menu items?

**Comment by brenoferreira** [comment]
Screen Shot 2020-01-27 at 12 02 14
What's this rectangle? Is it the visibility toggle?

**Comment by hugosolar** [comment]
Since there isn't mobile design for header yet I have't work on those styles

**Comment by brenoferreira** [comment]
@hugosolar should I wait for the mobile styles then?

**Comment by brenoferreira** [comment]
This PR is no longer valid because of the changes in the codebase in #89

**Comment by brylie** [comment]
@all-contributors please add @hugosolar for code

**Pull request closed without merging**
