### PR TITLE
Add a "compact" header to vocabulary

### LINKED ISSUE #464: A smaller version of the header component [Feature request]
## Problem
The CC Search Extension mockup uses a header component that any of the current Vocabulary header component is not able to  replicate. See the [Figma Mockup file](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=892%3A4577&viewport=505%2C72%2C0.28836095333099365) and a quick [Codepen](https://codepen.io/makkoncept/pen/LYGZgrX) for reference.

## Description

Some differences that I noticed:
- The height of the header seems to be little larger than the one in the mockup.
- The class of `has-text-tomato` class on `nav-item` links is not able to override the default `nav-item` color.
- The `nav-item` also has larger margin and font-size.
- Changing `logomark` icon with `search` icon does not work by default. Changing the `viewBox` attribute of `svg` element from `0 0 304 73` to  `0 0 170 50` does the trick but now the icon is not vertically alligned.

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by makkoncept**
## Fixes

Fixes #464 by @makkoncept 

## Description

Add a "compact" version of the header to vocabulary. This component will be used in the CC Search Extension ([see mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4577)).

The markup of this component is very minimal when compared to `Big` and `Small` headers because most of the classes present there like `has-dropdown`, `navbar-burger`, etc are not required since it is not expected that the header should change in "mobile" view (width of CC Search extension is ~640px)

## Screenshots

Screenshot from 2020-08-11 16-23-44

_Mimicking the view that will be used in CC Search Extension_ 
Screenshot from 2020-08-11 16-21-43

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by makkoncept** [comment]
@hugosolar @zackkrida   There is a small issue. In the "docs" tab in the storybook, the component is rendered as follows: 

Screenshot from 2020-08-11 17-01-09

This is because the current width of the viewport falls under "tablet". For eg: if I mimic the "mobile" view, then the component takes the intended form:

Screenshot from 2020-08-11 17-01-22

You can correct me if I am wrong, but I think this would not be a problem when using this component because the maximum width of extension popup is ~640px, therefore only the mobile view will trigger?

A solution for rendering the component correctly in the storybook would be to also add the same style rules for the `tablet` view. Shall I do that?

**Comment by zackkrida** [comment]
> A solution for rendering the component correctly in the storybook would be to also add the same style rules for the tablet view. Shall I do that?

Yes, this sounds like a good fix! @makkoncept

**Comment by makkoncept** [comment]
@zackkrida Done!

Screenshot from 2020-08-12 01-10-56

**Review by Dhruvi16 — APPROVED** [review]

**Review by zackkrida — APPROVED** [review]
👍

**Pull request merged**
