### PR TITLE
Replace src/stories/footer.stories.js with footer.stories.mdx

### LINKED ISSUE #229: Replace src/stories/footer.stories.js with MDX Docs
**Description**

**Problems solved**

**Alternatives**

**Additional context**

**Want to take up?**

Yes

### PR DESCRIPTION
**Pull request by kushaggarwal**
**Fixes**

Fixes #229 by @kushaggarwal

**Description**

This issue aims at the replacement of the footer.stories.js to footer.stories.mdx
**Type of PR**

This PR is a feature

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ ] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I have made the changes as per my understanding so can you please guide me for the changes and the improvements
Thank you

**Comment by kushaggarwal** [comment]
Please help @dhruvkb as I am not able to figure out what should be added in design :figmaConfig("")
Screenshot 2020-03-25 at 8 17 01 PM

**Comment by megha070** [comment]
Hey, @kushaggarwal by making use of "FigmaConfig" we are associating every story in the Vocabulary storybook with a Figma node from the Design Library.
So you need to add link of corresponding Figma Node from Design Library. You can find them here. (https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library)
Also, you need to import FigmaConfig from ./helpers instead of importing config from addon-designs
```
import { figmaConfig } from './helpers'
```

**Comment by kushaggarwal** [comment]
Thank You @megha070 
Will proceed accordingly

**Comment by megha070** [comment]
image
You have to include the highlighted part in the link in figmaConfig.
Also, I noticed by mistake you have deleted package-lock.json. You will need that in order to get your PR merged.

**Comment by kushaggarwal** [comment]
Yes, I noticed 
Thanks

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
Please help for the same as if it is right or not 
Thank you

**Comment by dhruvkb** [comment]
I'll review it later, you can work on the other issues for now.

**Comment by kushaggarwal** [comment]
Okay thank you vey much

**Pull request closed without merging**
