### PR TITLE
Add a compact image component and bookmark icon (to the image component)

### LINKED ISSUE #465: A modified image component for CC Search Extension [Feature Request]
## Problem
The CC Search Extension mockup uses a modified image component that is not currently present in CC Vocabulary. See the [Figma Mockup file](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) and a quick [Codepen](https://codepen.io/makkoncept/pen/MWKexxL) for reference.

## Description

Some differences that I noticed:

- The image component for extension won't be needing an image title. Though this can easily be done by not including the `image-title` div when dynamically building the component and appending them in the masonry grid in the extension.
- The space between the license icons is a bit less.
- A `bookmark` icon is also there on the top-right corner.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by makkoncept**
## Fixes

Fixes #465  by @makkoncept

## Description
The CC Search Extension [Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) uses an image component where we can see a bookmark icon appear at the top-right corner on hovering and also the license icons are smaller in size and have less padding when compared to the original image component present in the vocabulary. This PR adds the necessary style definitions so that this kind of image component can be natively supported by vocabulary.

## Technical details

- An implicit decision:  Due to the line-height of the license icons, the vertical padding was not needed for the compact version.
- Since the bookmarks icons are not available in the vocabulary, for now, I used the "sort" icon. Until then, this is a draft PR.

## Screenshots

Screenshot

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by makkoncept** [comment]
@hugosolar Can you provide an initial review. cc @dhruvkb @zackkrida

**Review by hugosolar — COMMENTED** [review]
it looks good to me but I'll wait until the font library is released before merging this PR. does that make sense to you?

**Comment by makkoncept** [comment]
@hugosolar Yes, sounds good. I may have to also tweak the spacing for the bookmarks icon.

**Review by zackkrida — APPROVED** [review]
I agree with all the existing discussion.

**Comment by makkoncept** [comment]
Updated screenshot : 
Screenshot from 2020-07-24 01-51-05

I have a general question. Is there room for a minor difference between components in vocabulary and their mockup in Figma? for example in spacing. Because for space around the bookmark icon, I have used `padding-*-small` which gives `8px` but there is small difference if you notice in the picture below (the version of the component in [Figma has](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4577)). Sorry if this sounds like a silly question but I wanted to be sure as this is my first time.

Screenshot from 2020-07-24 01-54-04

**Comment by zackkrida** [comment]
Hi @makkoncept this is a very good question. There are definitely current issues with icon spacing and alignment, I have a pr on our `fonts` repo that will fix _some_ of these: https://github.com/creativecommons/fonts/issues/110

I think your PR and mild spacing inconsistency is fine for now. Thank you for your attention to detail!

**Pull request merged**
