### PR TITLE
Fix card width issue on mobile

### LINKED ISSUE #860: Cards are not responsive in mobile view.
## Description
Cards are not responsive in mobile view, as fixed width in the pixels is defined there.

## Reproduction
Sidebar->cards section

## Resolution
Layouts _ Cards - PostVertical ⋅ Storybook

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by clasick**
## Fixes
Fixes #860 by @frappelatte28 

## Description
Cards are broken on lower resolution devices (like mobile). Issue was that the cards were having a static width set. This needed to be changed to max-width for lower resolution devices to scale it down but also not have ridiculously large card components on higher resolutions.

## Tests
Run Storybook and navigate to Cards section. Turn on Web Responsive Mode and choose a  mobile device and scroll around, observe that the cards are within the width of the image and nothing is broken.

## Screenshots
Before fix, as reported by @frappelatte28 :

card-width-issue
After this change:

card-width-issue-fix

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by fcoveram — APPROVED** [review]

**Comment by brylie** [comment]
@clasick, thank you so much for the contribution.

I'm going to close this pull request without merging the changes since it is stale and there are unresolved conflicts. Please feel free to re-open the pull request if you have the time to continue the task :smiley:

**Comment by clasick** [comment]
> @clasick, thank you so much for the contribution.
> 
> I'm going to close this pull request without merging the changes since it is stale and there are unresolved conflicts. Please feel free to re-open the pull request if you have the time to continue the task

@brylie Thanks for the update! If I'm understanding correctly, the only task left is to resolve the merge conflicts?

**Comment by brylie** [comment]
@clasick yes. Please resolve conflicts and re-open the pull request :-)

**Comment by clasick** [comment]
@brylie Fixed the conflicts. Could you reopen this pull request so I can update it? It only shows me an option to create a new one since this is closed as of now.

**Comment by brylie** [comment]
PR is open :-)

**Comment by clasick** [comment]
@brylie Thanks! Looks like the merges are reflected in the PR now.

On a side note, merging was done through a rebase. I see 15 files are shown as changed in the PR diff except only one is an actual change (it's showing the diff between when this PR was created and not what is the current state of the branch). I hope this would won't pollute commit history once it's merged?

**Comment by brylie** [comment]
@clasick I'd like to hold off from merging this pull request until the project restructuring is complete: #905

**Comment by brylie** [comment]
@clasick, we have recently refactored the project structure. Would you mind applying your fix against the new project structure?

**Comment by brylie** [comment]
This change was merged into main with attribution given to @clasick

**Pull request closed without merging**
