### PR TITLE
Cache node modules to improve CI workflow speed

### PR DESCRIPTION
**Pull request by SaurabhAgarwala**
## Fixes

Related to #331 by @dhruvkb

## Description

With this PR, in the CI workflow, the node modules will be installed and cached in the `Setup`job if there is a change in `package-lock.json` file. Then in subsequent jobs to `lint`, `unit tests` and `build`, the node modules won't be installed but be restored from the cache. It is expected that with this approach, the workflow run time will improve by about 45 seconds for each workflow run.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
This approach is leading to errors. I am looking into the solution for the same. Converting this PR to draft for time being.

**Comment by megha070** [comment]
@SaurabhAgarwala I was also going through some articles on how we can improve CI workflow. Came across this. In this PR you are trying to cache node_modules but according to below link. It is not recommended to cache node_modules as it can break across Node versions and won't work with npm ci. Hope this can be of help to you.
https://github.com/actions/cache/blob/master/examples.md#node---npm

**Comment by SaurabhAgarwala** [comment]
Yeah @megha070, even I came across this article before implementing. So even I discarded the idea initially. But later after a deeper thought, I felt it won't affect our use case as we are using a single node version which is defined in the workflow file itself. Also, `npm ci` isn't getting triggered in this workflow. So I went ahead to implement it.

**Comment by SaurabhAgarwala** [comment]
Closing the PR based on the discussion in the issue thread.

**Pull request closed without merging**
