### PR TITLE
Update tab component according to the Design Library

### LINKED ISSUE #369: The tab component doesn't follow the style defined in the Design Library
## Describe the bug
The active and inactive states of the tab component don't follow the style defined in the Design Library.
Screen Shot 2020-05-14 at 11 42 05

## Expected behavior
The active and inactive states have a different line weight and size, without padding. See the [mockup in Figma (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=6496%2C3630%2C1).

### LINKED ISSUE #471: Modified tab components [Feature request]
## Problem

I observed that `tabs` component used in the [CC Search Extension Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) have a different design. 

I see two new flavours of the component :

Screenshot from 2020-06-16 18-21-01

Screenshot from 2020-06-16 18-14-11

Maybe more discussion is needed for the second one. Is it really a tab component or something else(a header?). It do functions like a tab in the [Mockup](https://www.figma.com/proto/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=892%3A4577&viewport=505%2C72%2C0.28836095333099365&scaling=min-zoom).

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by makkoncept**
## Fixes

Fixes #471 by @makkoncept 

## Description

The [design library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6990%3A0&viewport=-2149%2C170%2C0.37196049094200134) has two types of tabs. This PR adds these to vocabulary.

- **Line tab**: For this, some modifications were made to the style rules of the current tab component of vocabulary.
- **Box Tab**: Extended the [Bulma version](https://bulma.io/documentation/components/tabs/#styles) of `is-boxed` tabs to fit the needs of Design Library.

## Screenshots

**Line tab**

_before_

Screenshot from 2020-07-28 02-25-05

_after_

Screenshot from 2020-07-28 02-23-36

**Box tab**
Screenshot from 2020-07-28 20-41-48

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by makkoncept** [comment]
@zackkrida There is a visible issue with this. When hovering inactive tabs, they are moving a bit because of the appearance of the border. I am not able to fix this :/

tab

**Comment by zackkrida** [comment]
@makkoncept i would reccommend always having a border under each item, but make it transparent when the tab isn't active. This should preserve proper spacing

**Comment by makkoncept** [comment]
@zackkrida  Works like a charm! Thanks :)
tab2

I'll now work on adding the box tab.

**Comment by zackkrida** [comment]
@panchovm could you review the gifs here and provide any feedback before I approve? Thank you 😄

**Comment by fcoveram** [comment]
It looks and works excellent. Thank you both.

**Comment by makkoncept** [comment]
Added box component. Please refer the GIF below


tab3

**Comment by makkoncept** [comment]
@zackkrida Is the naming correct? The story's name is `Box Tab` and the class name is `is-boxed`. Shall I also change the story name of the default tab from `Tab` to `Line Tab` (maybe to remain consistent with the design library) ?

**Review by zackkrida — CHANGES_REQUESTED** [review]
@makkoncept the existing naming is good! you can keep it. Two things for the box tab—the tab font should be smaller (our normal 16px font weight) and the tab content needs the same background color as the active tab

**Comment by makkoncept** [comment]
@zackkrida  Thanks for pointing out the background color issue. It was more serious because I forgot that the iframe background in the storybook was of `light-gray` color :sweat_smile: hence the following blunder

tabs6

Now, it's fixed.

tabs5

**Comment by makkoncept** [comment]
Hey, I found a small issue. In line-tab, the space between the tabs and the content is more (32px) than the current default (24px). Let me fix it.

Edit: fixed :+1:

**Review by zackkrida — APPROVED** [review]
Nice work!

**Pull request merged**
