### PR TITLE
Added focus style to button

### LINKED ISSUE #718: Button focus indicator is invisible on black background
## Description

The Vocabulary buttons have a box-shadow when they are focused. This looks consistent across browsers, and looks nice on the white background. However, on the black background, for example, in the global header or in the footer, the box-shadow becomes invisible. It is important for accessibility purposes for header/footer, as well as when we have a dark theme for Vocabulary.

We need the designs for additional focus styles to the interactive elements on the dark background. Then we can implement them in Vocabulary.

## Screenshots

The button focus style is visible on the white background as the pink shadow:
FocusStyle

The pink shadow is indiscernible on the black background:
FocusStyleBlack

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by SaravgiYash**
## Fixes

Fixes #718  by @obulat 

## Description
Added focus style to button in order to increase accessibility

## Technical details
Added outline: 1px solid $color-white;

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
I'm sorry, @Yashs911, I led you to the wrong line in the original issue. The correct class that should be targeted for the donate button is this:
    https://github.com/creativecommons/vocabulary/blob/8a8e370aecbfaa3311c6473eae07da8a8eebe4f9/packages/vocabulary/src/styles/footer.scss#L95

Also, the problem with adding an outline to a button is that outlines do not have rounded corners. And the solution to this is to use a white 'box-shadow', you can read more about it [here ](https://css-tricks.com/having-a-little-fun-with-custom-focus-styles/#apply-a-box-shadow).

**Comment by SaravgiYash** [comment]
@obulat I have made the required changes. Thanks for your guidance.
Should I change the width to 1px or 2px is fine?

**Comment by obulat** [comment]
focus
I think this looks fine. @panchovm , do you think this is the right style for outline here?

Although, I looked at the code again, and noticed another button in the footer. I think it would be even better to add a general rule for `.button` class in the footer, just underneath the styles for `a` in line 6. This way, it would be applied to both subscribe and donate buttons. Sorry for not noticing it earlier.

**Comment by SaravgiYash** [comment]
https://github.com/creativecommons/vocabulary/blob/b7eb16e62e472612a1a69a5fa6f10d9fa4074c6c/packages/vocabulary/src/styles/footer.scss#L6

@obulat Should I add the focus here or wait for @panchovm reply

**Comment by fcoveram** [comment]
It looks great @obulat and agree with your suggestion. All links should behave similarly.

**Review by obulat — APPROVED** [review]
Thank you for your help and your patience, @Yashs911 !

**Comment by SaravgiYash** [comment]
@dhruvkb @nimishbongale Can you please review and approve the PR

**Comment by nimishbongale** [comment]
@Yashs911 The PR has already been approved by @obulat. I'm sure this PR will be merged soon along with a few others!

**Comment by zackkrida** [comment]
Closed in favor of #758

**Pull request closed without merging**
