### PR TITLE
PR for Updating contribution guide with development environment setup instructions

### LINKED ISSUE #954: Update contribution guide with development environment setup instructions
We recently refactored the project but neglected to update the contribution guide. I.e., the README and contribution guide differ substantially, such as there being no Docker Compose file.

https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page
It would probably be a good idea to remove one of the two resources to prevent them from going out of sync.

## Task

- [ ] ensure the README contains accurate instructions for setting up a development environment
- [ ] if desirable, restore the Docker Compose file (for cases where `npm` is causing issues)
- [ ] copy any remaining salient information from the [Vocabulary / Contribution](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page) instructions to the README
- [ ] replace the Vocabulary / Contribution article with a link to the project README

### PR DESCRIPTION
**Pull request by Akpjunior94**
## Fixes

Fixes #954  by @brylie 

## Description

Instruction for setting up a development environment
Restoring docker-compose files for cases where npm is causing an issue
Updating vocabulary/Contribution instructions on the README
Linking the vocabulary/Contribution article.

 

 

## Checklist
 
- [x] I updated the instructions for setting up a development environment.
- [ ] My pull request targets the *main* branch of the repository.
- [ ] I restored docker-compose files.
- [ ] I linked the vocabulary/Contribution article.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by brylie** [comment]
@Akpjunior94, thanks for your contribution here. Would you mind contributing to the review process in pull-request #955, so we can converge on a good outcome without duplicating efforts?

**Comment by Akpjunior94** [comment]
Okay, @brylie I will do just that.

**Comment by brylie** [comment]
Closing this since we aren't currently using Docker.

**Comment by Akpjunior94** [comment]
> Closing this since we aren't currently using Docker.

Okay @brylie

**Comment by brylie** [comment]
@Akpjunior94 would you be interested in contributing to any task in our [Good Housekeeping milestone](https://github.com/creativecommons/vocabulary/milestone/1)?

**Pull request closed without merging**
