### PR TITLE
Fixing broken tests

### LINKED ISSUE #330: Fix broken tests and re-enable them
**Description**
Presently the card and header tests have been de-activated by changing the name from `.test.js` to `.test.js.x`. This is because the card tests are flaky (#327) and because there is an inexplicable error in the header test. The goal is to fix both test suites, update code, styling and snapshots as required and make them pass.

**Reproduction**
Re-enable the tests and run on GitHub Actions.

**Expected behavior**
Tests should pass.

### PR DESCRIPTION
**Pull request by arushivii**
## Fixes

Fixes #330 by @dhruvkb

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by arushivii** [comment]
A lot of tests are failing, guide please @dhruvkb

**Comment by dhruvkb** [comment]
@av-00 the issue exists precisely because I don't know what the underlying cause is. If I did, I would've fixed the issue myself.

**Comment by arushivii** [comment]
@dhruvkb  What i'm trying to say that the issue is not just with header and cards but other tests as well, and there might be different issues addressing the same problem.

**Comment by dhruvkb** [comment]
Closing because visual regression testing is disabled till we can fix some stability issues in the system.

**Pull request closed without merging**
