### PR TITLE
Dark mode for our storybooks

### PR DESCRIPTION
**Pull request by nimishbongale**
## Fixes
Fixes #739  by @nimishbongale 

## Description

Uses the [https://github.com/hipstersmoothie/storybook-dark-mode](https://github.com/hipstersmoothie/storybook-dark-mode) addon alongwith storybook/theming to customise the dark mode for our storybooks.

### light
light

### dark
dark

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Can we keep the theme files that are common in all Storybooks in a common directory? I'm thinking of something like a `_common/` directory inside `packages/` (or whatever the monorepo convention may be for such shared files).

**Comment by nimishbongale** [comment]
> Can we keep the theme files that are common in all Storybooks in a common directory?

@dhruvkb 

Yes, we could do that. I was thinking maybe once we compose the storybooks together the duplication issue would go away. But turns out even after composing the storybooks the dark mode customisation is still needed on an individual storybook level. 

[ReactJS uses the folder name `/shared`](https://github.com/facebook/react/tree/master/packages/shared) inside `/packages`. Maybe we should have something similar?

**Review by zackkrida — CHANGES_REQUESTED** [review]
Please revert the `packages/*` change, and make `shared` an _actual_ package by adding a `package.json` file:

```
{
  "private": true,
  "name": "@creativecommons/shared",
  "version": "2020.11.4"
}
```

We want to be strict about making sure everything in `packages` is actually a package.

Please also import from the shared package like this:

`import { light, dark } from '@creativecommons/shared/theme'`

**Comment by nimishbongale** [comment]
> We want to be strict about making sure everything in `packages` is actually a package.

Yes! @zackkrida  

I discussed the same with @dhruvkb just yesterday! Here are my findings:

> Okay, so I've come across a very interesting hurdle 🤔 
> Will the folder we create for common files within the monorepo be a dummy ad-hoc package in itself?
> If yes:
> This shared package would then need to be installed before any other packages are installed as they are dependent on it.
> If no:
> Dependency management becomes an issue. I've tried isolating the theme.js file separately but its dependent on core-js at a minimum 😅

**Comment by zackkrida** [comment]
> This shared package would then need to be installed before any other packages are installed as they are dependent on it.

I'm not exactly sure what you mean here. So as long as all the packages using `@creativecommons/shared` specify it in their `package.json` as a dependency/devDependency, it'll be linked and added to their individual `node_modules` folders whenever `npm install` or `npm run setup` is run in the repo root.

There may be an issue i'm forgetting?

**Comment by nimishbongale** [comment]
> So as long as all the packages using `@creativecommons/shared` specify it in their `package.json` as a dependency/devDependency, it'll be linked and added to their individual `node_modules` folders 

Yep, this is what I meaning to say! 😄 

The package would basically be like an internal dependency. I'm now wondering maybe a lot of common things could be potentially pulled out to this package!

**Review by zackkrida — APPROVED** [review]
🎉

**Pull request merged**
