### PR TITLE
Add padding to text button for mobile-friendliness

### LINKED ISSUE #843: Text button are not mobile friendly due to height
## Description

Currently, the text button doesn't have padding, so its height becomes too small for tapping and fails mobile-friendliness criteria in Chrome Lighthouse. 

## Reproduction

1. Stack several text buttons vertically.
2. Run generate Lighthouse report in Google Chrome.
3. Look at the 'Tap targets are not sized properly' section.
4. See error.

## Expectation

Tap targets should have a height that makes it easy to tap. Text button should have padding.

## Screenshots

image

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #843 by @obulat

## Description

This PR adds padding to the text button to make the tappable height large enough.  On the screenshot, I added white background on hover to make the tappable area visible. I didn't add the background change in the code, so on hover only underline appears. Is this the correct behavior for the text button, @panchovm ?

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by fcoveram** [comment]
The idea of text button is that behaves as text rather than a button. That said, the padding should not exist by default. Regarding the hover state, I suggest eliminating the background color.

I agree with you on the tapable area, especially on mobile devices. However, that area can be defined by adding margins, paddings between elements rather than a definition for the button.

**Comment by obulat** [comment]
> The idea of a text button is that behaves as text rather than a button. That said, the padding should not exist by default. Regarding the hover state, I suggest eliminating the background color.
> 
> I agree with you on the tappable area, especially on mobile devices. However, that area can be defined by adding margins, paddings between elements rather than a definition for the button.

We can increase the tappable area by adding **transparent** padding around the text button. This way, the button will look and behave just like text, but the clickable area will be larger. 

If we don't add any padding (which is invisible, anyway), even if we do add margin, the clickable area will stay small, and the button will fail [this Google SEO audit](https://web.dev/tap-targets/).

**Comment by fcoveram** [comment]
You are right. Then let's go with the transparent padding. Thanks Olga. Great work

**Comment by obulat** [comment]
> You are right. Then let's go with the transparent padding. Thanks Olga. Great work

Thank you, Francisco! I hope great designs will become an accessible and user-friendly web pages.

**Review by zackkrida — APPROVED** [review]

**Pull request merged**
