### PR TITLE
Add 'normal' and 'disabled' styles to buttons

### PR DESCRIPTION
**Pull request by obulat**
## Description

This PR adds styles for 'normal'-sized button and `disabled` buttons. Normal-sized buttons are used in Chooser's stepper ('Previous' - 'Next')

## Screenshots

AddedButtonStyles
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
A few things:

- Would `[disabled] {}` be a better css rule than `.disabled`, to support the native `<button disabled>Click me</button>` property? Could also do both.
- @panchovm which button size should be the 'default': _normal_ or _middle_? @obulat depending on this answer we might want to switch the default button styles and make a `&.middle {}` variation instead

**Comment by obulat** [comment]
> * Would `[disabled] {}` be a better css rule than `.disabled`, to support the native `<button disabled>Click me</button>` property? Could also do both.

Sure! I forgot about the native  `[disabled]`. I don't think we would need the separate `.disabled` class, then.

> * @panchovm which button size should be the 'default': _normal_ or _middle_? @obulat depending on this answer we might want to switch the default button styles and make a `&.middle {}` variation instead

I'll make changes after @panchovm 's reply.

**Comment by fcoveram** [comment]
Hi @zackkrida @obulat the button size must be `normal`.

**Review by zackkrida — APPROVED** [review]
Great restructuring. These stories are now much more useful.

**Pull request merged**
