### PR TITLE
Monorepo migration

### PR DESCRIPTION
**Pull request by zackkrida**
This pull request converts `creativecommons/vocabulary` to a monorepo, including three total packages under one repository:

- `creativecommons/vocabulary`
- `creativecommons/fonts`
- `creativecommons/vue-vocabulary`

Special care has been taken to preserve the Git history of each package, using the excellent [tomono](https://github.com/hraban/tomono) script. All repositories were merged into their respective `packages/{package-name}` directories in the root of a blank repo. Then, root configuration for `lerna` was implemented, all `.github` directory files were merged and moved to the root, and ci/cd scripts were rewritten to be scoped to the proper packages.

The `Files changed` gitHub tab isn't particularly useful here—anyone reviewing this PR should confirm that they can view an accurate git history for various files, and that the development + build scripts for each package still work.

Note that we are not using the full power of monorepos here—this PR aims to do the initial minimum so that each package can be worked on and deployed under one roof. Separate tickets will be made for enhancements and improvements to this workflow.

All CI scripts are confirmed working—one can view https://github.com/creativecommons/vocabulary/actions and see the successful CI run completed for each:

Screen Shot 2020-08-30 at 1 45 53 PM

CI scripts have been altered to _only_ run when files in a particular package have been updated. For example, if a PR only touches files in the `fonts` package, only the fonts ci job will run. 

The one check that _is_ failing is the Netlify storybook deploy—we'll have to edit the configuration on Netlify to deploy properly.

Additionally, the original `fonts` and `vue-vocabulary` repositories should be archived—pull requests that add archive notices have been made for each repo:

- https://github.com/creativecommons/fonts/pull/138
- https://github.com/creativecommons/vue-vocabulary/pull/253

These repositories should be archived through the GitHub UI when these PRs are merged.

## Things we'll want to do after this is merged

- Move eslint, prettier, and other development libraries/config files into the project root
- Make a private `packages/docs` package that is a unified storybook installation for all other packages, removing anything related to storybook from the other packages

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
@zackkrida can you point me to the major changes that actually need review? 402 files is a lot 😅 and I suppose most of them were simply moved over from the other two repos.

**Comment by zackkrida** [comment]
> The `Files changed` GitHub tab isn't particularly useful here—anyone reviewing this PR should confirm that they can view an accurate git history for various files, and that the development + build scripts for each package still work.

@dhruvkb I would stick to this suggestion. Pull down locally, peek at the workflow files in `.github/`, cd into each package and make sure the tests + storybook instances still work.

The only real file changes are:

- created private root `package.json`
- edits to each package's `package.json` (added correct path to repo)
- fix paths in `.github/` ci/cd scripts; trigger ci only if particular package is edited
- deleted per-package, CODEOWNERS, CONTRIBUTING, files

**Comment by dhruvkb** [comment]
That's very helpful. Thanks!

**Comment by kgodey** [comment]
Closing, this repo will be archived soon. https://github.com/creativecommons/vocabulary/pull/613

**Comment by kgodey** [comment]
Sorry, accidentally closed this.

**Review by aldenstpage — APPROVED** [review]
Great job! Of course, it's not possible to review a change of this size, but I can see that care has been put into making the CI work for this new architecture (some of which I will steal for the bundled projects in the cccatalog-api repo) and that I can build the project locally.

**Comment by kgodey** [comment]
@zackkrida Please update required status checks for this and the other repos when this is done.

See: https://github.com/creativecommons/ccos-scripts/blob/master/normalize_repos/branch_protections.py

**Comment by zackkrida** [comment]
@kgodey Great, will do. I'll definitely need to wait until after merging to update. Some of these status checks are _optional_ (i.e, they are only triggered if a particular package is worked on) so I will figure out the best way to configure them.

**Pull request merged**
