### PR TITLE
Change p tag to div in footer

### LINKED ISSUE #387: address tag inside p in footer
**Description**
While working on https://github.com/creativecommons/chooser/issues/161 I came across this problem.
Currently the storybook for footer contains this following code - 

```
 <p>
    <address class="margin-bottom-normal"> Creative Commons <br> PO Box 1866, Mountain View CA 94042</address>
    <a href="mailto:info@creativecommons.org" class="mail">info@creativecommons.org</a>
    <a href="tel://+1-415-429-6753" class="phone">+1-415-429-6753</a>
</p>
```
However, according to the [Official HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) 

> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.

This causes the `p` tag to close immediately, for example when used with Vue lint. I believe this is also causing the render error in the storybook.

**Reproduction**
Include the code in a Vue JS file and run `vue-cli-service lint`. This closed the `<p>` tag and reports `error: Parsing error: x-invalid-end-tag (vue/no-parsing-error)`

**Expected behavior**
The code should compile correctly.

**Screenshots**

This is the screenshot from the stroybook when you click on "show code". The code fails to render.

Screenshot_20200516_205825

**Want to take up?**

Yes

### PR DESCRIPTION
**Pull request by heraldofsolace**
## Fixes

Fixes #387  by @Herald-Of-Solace

## Description
This pull request changes the `<p>` tag to `<div>` tag to make it into a valid HTML

## Tests
Visit the [HTML validator](https://validator.w3.org/nu/#textarea) and paste in the code for the footer and click "Check"

There should be one error because you do not have an `<html>` tag. But there should be no errors related to the `<p>` tag

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [] I added tests for the changes I made (if applicable).
- [] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@Herald-Of-Solace please resolve the conflicts so that we may merge this PR.

**Comment by heraldofsolace** [comment]
@dhruvkb I have fixed the conflicts

**Review by dhruvkb — APPROVED** [review]

**Review by dhruvkb — COMMENTED** [review]
@Herald-Of-Solace while these changes are good to go as they fix a problem, would you be interested in resolving https://github.com/creativecommons/vocabulary/issues/387#issuecomment-629978836 in this PR itself?

**Comment by heraldofsolace** [comment]
@dhruvkb Sure!

**Comment by heraldofsolace** [comment]
@dhruvkb Done

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
